# Generated by Django 4.1.1 on 2022-09-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='no album title', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='no song title', max_length=100),
        ),
    ]
